import { type Event, type DOMQuakeOptions } from "./types.ts";
import { EventEmitter } from "./EventEmitter.js";
export declare class DOMQuake extends EventEmitter<Event> {
    private readonly options;
    private readonly emitOnTick;
    private subtreeSizes;
    private nodeDOMDepths;
    private currentState;
    private domDepth;
    private domIntensity;
    private totalNodeCount;
    private decayedIntensity;
    private mutationEventMap;
    private pendingMutationRecords;
    private hasStaleDOMMeasures;
    private mutationObserver;
    private tickInterval;
    private transitionTicks;
    constructor(options?: Partial<DOMQuakeOptions>, emitOnTick?: boolean);
    private reset;
    private isSkipped;
    private filterSkippedNodes;
    private resolveTarget;
    private computeStructuralFactor;
    private computeHTMLDeltaFactor;
    private computeWeight;
    private pruneStaleEvents;
    private computeWindowSum;
    private measureNodeDepth;
    private measureDOM;
    private flushPendingRecords;
    private tick;
    observe(): this;
    disconnect(): this;
}
